
    <!-- <div id="mpd" class="container-fluid">
        <p>Last updated: %{Mod Date}%</p>
        <a href="#top" aligh="right" id="to-top-button" title="Return to Top"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
    </div>
</div> -->

<br>
<br>
<br>

<nav class="small navbar fixed-bottom navbar-light bg-light" style="height:35px;">
    <p class="navbar-text mr-auto" style="height:20px;">
        <a href="#top" id="to-top-button" title="Return to Top">
            <i class="fa fa-arrow-up" aria-hidden="true"></i>
            Go to Top
        </a>
    </p>
    <p class="navbar-text" style="height:20px;">
        Last updated: %{Mod Date}%
    </p>
</div>
